import {
  serviceGuideEditorial,
  type ServiceGuideEditorial,
} from "./service-guide-editorial";

export type ServiceGuide = {
  slug: string;
  routePath?: string;
  title: string;
  shortTitle: string;
  summary: string;
  metaTitle?: string;
  metaDescription?: string;
  breadcrumbParent?: string;
  covers: string[];
  methods: string[];
  prognosis: string;
  timeline: string;
  factors: string[];
  precautions: string[];
  textbookBasis?: string;
  careContext?: string;
  editorial?: ServiceGuideEditorial;
  relatedLinks?: Array<{ href: string; label: string }>;
};

export const serviceGuides: ServiceGuide[] = [
  {
    slug: "homecare-physiotherapy",
    routePath: "/home-physiotherapy",
    title: "Home Physiotherapy: Personalised Treatment at Home",
    shortTitle: "Homecare Physiotherapy",
    summary: "Home physiotherapy brings assessment-led care into the environment where recovery actually happens, with a progressive plan for pain, mobility, strength, and daily function.",
    metaTitle: "Home Physiotherapy in India | Goswami Rehab",
    metaDescription: "Home physiotherapy in 45 listed cities for pain, injury, post-surgery, and neurological rehabilitation. Share your locality and goals. Ask first today.",
    covers: ["Back, neck, and joint pain physiotherapy", "Post-surgery rehabilitation", "Fracture and soft-tissue injury rehabilitation", "Mobility limitations and deconditioning", "Neurological and complex case rehabilitation"],
    methods: ["History, movement, strength, balance, and functional assessment", "Education, pacing, and a personalised home exercise programme", "Progressive mobility, strengthening, balance, gait, and task practice", "Manual techniques or symptom-modulation strategies when clinically appropriate", "Caregiver training and home-safety recommendations"],
    prognosis: "Many uncomplicated musculoskeletal problems improve over 2–12 weeks. Complex neurological, post-operative, or long-standing conditions usually need a longer programme with progress measured in function rather than pain alone.",
    timeline: "Acute pain or minor injury: approximately 2–6 weeks. Post-operative recovery: commonly 6–16 weeks. Complex or neurological rehabilitation: often 3–12+ months, with visit frequency changing as independence improves.",
    factors: ["Diagnosis and tissue healing", "Medical stability and co-existing conditions", "Baseline strength, balance, and mobility", "Regular practice between visits", "Home layout, caregiver support, sleep, and nutrition"],
    precautions: ["The plan must follow surgical or physician restrictions.", "New chest pain, severe breathlessness, fainting, sudden weakness, or rapidly worsening neurological symptoms need urgent medical assessment.", "An exercise programme should follow an individual assessment, not a generic online routine."],
    textbookBasis: "Kisner & Colby, Therapeutic Exercise; O’Sullivan, Physical Rehabilitation; Goodman & Fuller, Pathology for the Physical Therapist.",
    editorial: serviceGuideEditorial["home-physiotherapy"],
  },
  {
    slug: "cardiopulmonary-rehabilitation",
    title: "Cardiopulmonary Rehabilitation: Breathing and Endurance Training",
    shortTitle: "Cardiopulmonary Rehabilitation",
    summary: "Structured rehabilitation for people whose heart or lungs limit activity, with monitored exercise and education designed around safe functional goals.",
    metaDescription: "Cardiopulmonary rehabilitation for breathing, endurance, cardiac recovery, COPD, fatigue, and safe activity progression, guided by medical stability needs.",
    covers: ["COPD and pulmonary rehabilitation", "Cardiac rehabilitation after bypass and other procedures", "Heart failure rehabilitation when medically stable", "Reduced exercise tolerance after hospitalisation", "Breathlessness, fatigue, and deconditioning"],
    methods: ["Baseline symptom, medication, oxygen, pulse, blood-pressure, and activity review", "Breathing control, paced breathing, and energy-conservation education", "Graded aerobic and strengthening exercise within prescribed limits", "Airway-clearance techniques when indicated and taught safely", "Monitoring of symptoms and recovery during and after exercise"],
    prognosis: "Exercise tolerance and confidence can improve with consistent pulmonary or cardiac rehabilitation, but the underlying heart or lung disease may remain. Prognosis depends on medical stability, disease severity, oxygen needs, exacerbations, and adherence.",
    timeline: "A structured programme is commonly 6–12 weeks, often 2–3 supervised sessions per week in guideline-based programmes. Homecare frequency is individualised; maintenance exercise may be needed for months or ongoing.",
    factors: ["Cardiac or respiratory diagnosis and severity", "Oxygen prescription and clinical stability", "Recent admissions or exacerbations", "Smoking status and medication adherence", "Ability to practise safely between sessions"],
    precautions: ["Exercise intensity must be cleared and adjusted for the person’s medical status.", "Stop and seek urgent help for chest pressure, severe or unusual breathlessness, faintness, blue lips, confusion, or palpitations with collapse.", "Never change prescribed oxygen flow or cardiac medication without the treating clinician."],
    textbookBasis: "ACSM’s Guidelines for Exercise Testing and Prescription; Frownfelter & Dean, Cardiovascular and Pulmonary Physical Therapy; Braddom, Physical Medicine and Rehabilitation."
  },
  {
    slug: "advanced-complex-case-recovery",
    title: "Advanced Complex Case Recovery: Rehabilitation After Critical Illness",
    shortTitle: "Advanced Complex Case Recovery",
    summary: "Coordinated rehabilitation for patients whose strength, breathing, cognition, movement, or independence has been affected by critical illness or multiple conditions.",
    metaDescription: "Home rehabilitation for post-ICU weakness, neurological illness, prolonged hospitalisation, and complex recovery, with assessment-led goals for function.",
    covers: ["Post-ICU rehabilitation for weakness and deconditioning", "Stroke, brain injury, and spinal cord injury rehabilitation", "Guillain–Barré rehabilitation and severe neurological illness", "Multi-system illness and prolonged hospitalisation", "Loss of mobility and activities of daily living"],
    methods: ["Review of discharge information, precautions, medications, and current medical stability", "Strength, sensation, tone, balance, cognition, breathing, transfers, and gait assessment", "Low-load functional practice progressed to strengthening and endurance", "Positioning, contracture prevention, fatigue management, and caregiver training", "Team communication with doctors, nurses, occupational therapists, and speech therapists when needed"],
    prognosis: "Recovery is highly variable. Early gains may be seen over weeks, while severe weakness, neurological injury, swallowing or cognitive problems, and complications can extend recovery over many months. A plateau in one measure does not always mean functional recovery has stopped.",
    timeline: "Initial reconditioning often takes 4–12 weeks. Moderate to severe post-ICU or neurological recovery commonly continues for 3–12 months or longer, with reassessment at regular milestones.",
    factors: ["Cause and severity of the illness", "Length of ICU or hospital stay", "Pre-existing strength and independence", "Cognition, mood, sleep, nutrition, and fatigue", "Complications and the availability of caregiver support"],
    precautions: ["Progression must be coordinated with medical restrictions, lines, wounds, oxygen, and blood-pressure responses.", "New confusion, fever, severe breathlessness, chest pain, fainting, or a sudden neurological change needs medical review.", "Caregivers should be taught safe handling rather than lifting or pulling a patient without instruction."],
    textbookBasis: "Braddom, Physical Medicine and Rehabilitation; O’Sullivan, Physical Rehabilitation; Umphred’s Neurological Rehabilitation."
  },
  {
    slug: "clinical-assessment-evaluation",
    title: "Clinical Assessment & Evaluation: Measuring the Right Problems",
    shortTitle: "Clinical Assessment & Evaluation",
    summary: "A structured assessment identifies the causes and consequences of a problem, sets measurable goals, and determines whether physiotherapy is appropriate or medical referral is needed.",
    metaDescription: "Physiotherapy assessment for pain, movement, strength, balance, gait, breathing, and measurable recovery goals, with referral when review is needed today.",
    covers: ["Pain and movement problems", "Strength, range, balance, and gait", "Neurological screening", "Breathing and exercise tolerance", "Transfers, stairs, and activities of daily living"],
    methods: ["Subjective history, goals, medication, medical history, and red-flag screening", "Objective tests selected for the patient’s condition and function", "Standardised measures where suitable, repeated to track change", "Explanation of findings and shared goal-setting", "A written home programme and review plan"],
    prognosis: "An assessment does not promise an outcome. It provides a baseline and identifies modifiable factors. The expected course becomes clearer after observing response to treatment and reviewing objective function over time.",
    timeline: "A first assessment commonly takes 45–90 minutes. Reassessment is often useful after 2–6 weeks for musculoskeletal problems and at planned milestones for longer neurological or cardiopulmonary programmes.",
    factors: ["Quality of the diagnosis and baseline measures", "Patient goals and meaningful activities", "Severity, irritability, and medical complexity", "Response to the initial programme", "Consistency of follow-up and home practice"],
    precautions: ["Referral is appropriate when findings suggest fracture, infection, serious neurological compromise, uncontrolled cardiac or respiratory disease, or another condition outside physiotherapy scope.", "Assessment findings should be explained clearly and updated when symptoms change."],
    textbookBasis: "Magee, Orthopedic Physical Assessment; O’Sullivan, Physical Rehabilitation; Goodman & Fuller, Pathology for the Physical Therapist."
  },
  {
    slug: "sports-enhancement-consultation",
    routePath: "/sports-injury-rehabilitation",
    title: "Sports Injury Rehabilitation: A Criteria-Led Return to Activity",
    shortTitle: "Sports Injury Rehabilitation",
    metaTitle: "Sports Injury Rehabilitation | Goswami Rehab",
    metaDescription: "Sports injury rehabilitation with strength, balance, and sport-specific progression after injury. Share goals and follow medical clearance when required.",
    breadcrumbParent: "Rehabilitation",
    summary: "Sports injury rehabilitation builds capacity after an injury through assessment, progressive loading, and sport-specific practice shaped by symptoms and medical guidance.",
    careContext: "The aim is a considered return to training and daily activity, not simply an early return date. Readiness depends on the injury, healing, confidence, strength, and the demands of the sport.",
    covers: ["Movement and mobility limitations", "Strength and power development", "Running, jumping, landing, and change-of-direction skills", "Training-load and recovery planning", "Return to sport after injury clearance"],
    methods: ["Review of injury history, medical advice, training demands, and current symptoms", "Assessment of movement, strength, balance, and sport-specific tasks where appropriate", "Progressive mobility, resistance, running, jumping, or agility practice matched to healing", "Workload and recovery planning with clear symptom-monitoring guidance", "Coordination with the treating clinician or coach when consented and useful"],
    prognosis: "Recovery depends on the injury, tissue healing, associated conditions, and response to progressive activity. Return readiness is assessed through function and sport demands; no fixed date or performance outcome can be guaranteed.",
    timeline: "The plan and review interval depend on the injury and any medical restrictions. A minor strain and a surgical ligament injury require different progressions; the treating team sets milestones after assessment.",
    factors: ["Injury diagnosis and healing stage", "Pain, swelling, strength, control, and confidence", "Sport-specific demands and training volume", "Sleep, recovery, and consistency", "Medical clearance and communication across the care team"],
    precautions: ["Do not train through new instability, significant swelling, severe pain, or loss of function.", "Follow the surgeon’s or physician’s return-to-sport restrictions.", "Seek urgent assessment for a suspected fracture, major head injury, collapse, chest pain, or new neurological symptoms."],
    textbookBasis: "Brukner & Khan’s Clinical Sports Medicine; Kisner & Colby, Therapeutic Exercise.",
    editorial: serviceGuideEditorial["sports-injury-rehabilitation"],
  },
  {
    slug: "functional-training",
    title: "Functional Training: Building Strength for Daily Life",
    shortTitle: "Functional Training",
    summary: "Task-focused exercise that helps a person stand, walk, reach, lift, climb stairs, and participate in daily life with better control and confidence.",
    metaDescription: "Functional training physiotherapy for standing, walking, transfers, stairs, balance, strength, and daily tasks, progressed for safety and personal goals.",
    covers: ["Reduced strength after illness or inactivity", "Difficulty with transfers, stairs, or walking", "Work and household task demands", "Balance and confidence in movement", "General conditioning for independent living"],
    methods: ["Baseline testing of strength, balance, mobility, and task performance", "Sit-to-stand, step, reach, carry, gait, and balance practice", "Progressive resistance and aerobic conditioning", "Task modification and safe technique coaching", "Home-based practice using available furniture and space"],
    prognosis: "Strength and task confidence can improve when exercise is progressive and performed consistently. The rate is slower when there is severe weakness, pain, neurological impairment, or medical instability.",
    timeline: "Noticeable early changes may occur in 4–8 weeks. Building useful strength and endurance commonly takes 8–16 weeks, with maintenance exercise continuing thereafter.",
    factors: ["Starting strength and balance", "Pain and joint tolerance", "Neurological or cardiopulmonary limitations", "Frequency and progression of exercise", "Safety and support in the home"],
    precautions: ["Exercises must be scaled to prevent falls and excessive fatigue.", "Use a prescribed walking aid and have supervision when advised.", "Dizziness, fainting, chest pain, or unusual breathlessness requires stopping and medical review."],
    textbookBasis: "Kisner & Colby, Therapeutic Exercise; ACSM’s Guidelines for Exercise Testing and Prescription; O’Sullivan, Physical Rehabilitation."
  },
  {
    slug: "nutritional-consultation",
    routePath: "/nutritionist-dietitian-online",
    title: "Online Nutritionist & Dietitian Consultation",
    shortTitle: "Nutritionist & Dietitian Online",
    metaTitle: "Online Nutritionist & Dietitian | Goswami Rehab",
    metaDescription: "Online nutritionist and dietitian consultations for practical food goals, recovery support, and health needs. Ask if this service fits your concern today.",
    breadcrumbParent: "Nutrition",
    summary: "Online nutrition consultation can help turn health, recovery, and food goals into realistic routines shaped by medical needs, preferences, and everyday life.",
    careContext: "The consultation begins with your goals and context. Any plan should respect medical conditions, medicines, appetite, culture, budget, and whether a registered dietitian or doctor needs to lead the care.",
    covers: ["Food routines that support rehabilitation and daily energy", "Hydration, appetite, and meal-planning questions", "Nutrition habits related to weight-management goals", "Practical planning around activity and recovery", "Referral for medical nutrition needs outside the service scope"],
    methods: ["Review of food pattern, goals, medicines, health history, and preferences", "Collaborative goal-setting with realistic, culturally familiar choices", "Education about meal structure, hydration, and activity-related needs", "Follow-up to check practicality, tolerance, and any new concerns", "Coordination or referral when medical nutrition therapy is required"],
    prognosis: "Nutrition guidance can support daily routines and rehabilitation participation, but it does not diagnose or cure disease. Progress varies with health, circumstances, and whether additional clinical care is needed.",
    timeline: "The first consultation establishes priorities and an appropriate next step. Follow-up timing is agreed around the goal and health context; there is no fixed programme or promised result.",
    factors: ["Medical conditions, medicines, and symptoms", "Food access, culture, budget, and preparation support", "Appetite, sleep, activity, and rehabilitation needs", "Personal goals and readiness for change", "Whether a registered dietitian or physician should lead care"],
    precautions: ["People with kidney, liver, heart, diabetes, swallowing, or eating-related conditions may need a registered dietitian or doctor.", "Do not start restrictive diets or supplements based only on general information.", "Seek medical review for unintentional weight loss, persistent vomiting, dehydration, or repeated choking."],
    textbookBasis: "Krause and Mahan’s Food & the Nutrition Care Process.",
    editorial: serviceGuideEditorial["nutritionist-dietitian-online"],
  },
  {
    slug: "rehabilitation-programs",
    title: "Rehabilitation Programs: Structured Recovery From Surgery or Injury",
    shortTitle: "Rehabilitation Programs",
    summary: "A staged programme turns assessment findings into practical milestones for restoring movement, strength, endurance, and independence.",
    metaDescription: "Structured rehabilitation programmes after surgery or injury, using milestones for movement, strength, endurance, independence, and return to daily life.",
    covers: ["Knee replacement rehabilitation and hip replacement rehabilitation", "Fracture and orthopaedic rehabilitation", "Post-surgery mobility rehabilitation", "Neurological rehabilitation programmes", "Return to work, sport, and daily activities"],
    methods: ["Baseline assessment and shared functional goals", "Protection and symptom control during the early phase", "Progressive range of motion, strength, balance, endurance, and task practice", "Home exercise and caregiver instruction", "Regular reassessment with progression or referral when recovery differs from expectation"],
    prognosis: "A rehabilitation programme improves the chance of regaining function, but the final result depends on the injury or operation, complications, baseline health, and participation. Milestones should be individualised rather than guaranteed.",
    timeline: "Many uncomplicated orthopaedic programmes run 6–16 weeks. Joint replacement rehabilitation commonly progresses over 3–6 months. Fracture healing and complex neurological rehabilitation may require 3–12 months or longer.",
    factors: ["Surgical or injury severity and healing status", "Pain, swelling, and range of motion", "Strength, balance, and confidence", "Medical conditions and complications", "Adherence, sleep, nutrition, and home support"],
    precautions: ["Follow the surgeon’s weight-bearing, movement, wound, and lifting restrictions.", "Sudden swelling, wound drainage, fever, calf pain, chest pain, or sudden loss of function needs urgent medical review.", "Progression should be based on examination findings and functional milestones."],
    textbookBasis: "O’Sullivan, Physical Rehabilitation; Kisner & Colby, Therapeutic Exercise; Braddom, Physical Medicine and Rehabilitation."
  },
  {
    slug: "back-pain-physiotherapy",
    routePath: "/back-pain",
    title: "Low Back Pain Physiotherapy: Assessment and Recovery",
    shortTitle: "Back Pain Physiotherapy",
    metaTitle: "Back Pain Physiotherapy | Goswami Rehab",
    metaDescription: "Back pain physiotherapy with assessment, pacing, strength, and graded activity guidance. Share symptoms and goals; individual plans need clinical review.",
    breadcrumbParent: "Pain & Mobility",
    summary: "Low back pain physiotherapy starts with an assessment that connects back symptoms with movement, strength, nerve function, daily tasks, and the goals that matter to you.",
    careContext: "The focus is not only on reducing pain. The assessment looks at what the back problem is stopping you from doing—such as sitting, lifting, sleeping, working, or walking—and uses those tasks to shape a graded plan.",
    covers: ["Lower back pain and recurring flare-ups", "Back pain affecting sitting, lifting, walking, or sleep", "Sciatica-like leg symptoms that need screening", "Reduced strength or confidence after inactivity", "Work, household, and return-to-activity planning"],
    methods: ["History of symptoms, irritability, work demands, sleep, and previous episodes", "Screening of movement, hip and lower-limb strength, sensation, reflexes, and function", "Education about staying safely active and avoiding unnecessary bed rest", "Progressive trunk, hip, and whole-body strengthening matched to tolerance", "Pacing and graded return to lifting, walking, work, or sport"],
    prognosis: "Many uncomplicated episodes improve with time, education, and a progressive plan, but recovery varies. Leg weakness, neurological changes, trauma, or systemic symptoms can change the assessment and need medical review.",
    timeline: "A first assessment commonly takes 45–90 minutes. A review after 2–6 weeks can help adjust the programme, while recurring or persistent symptoms may need a longer capacity-building plan.",
    factors: ["Symptom irritability and duration", "Nerve-related signs or neurological findings", "Sleep, stress, work demands, and general conditioning", "Confidence with movement and consistency of practice", "Medical history and response to the initial plan"],
    precautions: ["Seek urgent medical assessment for new bladder or bowel changes, numbness around the groin, rapidly worsening leg weakness, major trauma, fever with severe back pain, or unexplained weight loss.", "Back pain is not diagnosed from an online description or scan alone.", "Exercises should be selected after assessment and modified if symptoms worsen or new neurological signs appear."],
    textbookBasis: "NICE NG59, Low back pain and sciatica in over 16s; O’Sullivan, Physical Rehabilitation; Kisner & Colby, Therapeutic Exercise.",
    editorial: serviceGuideEditorial["back-pain"],
    relatedLinks: [
      { href: "/blog/physiotherapy-for-low-back-pain", label: "Read the low back pain physiotherapy guide" },
      { href: "/services/clinical-assessment-evaluation", label: "Explore clinical assessment and evaluation" },
      { href: "/home-physiotherapy", label: "See homecare physiotherapy options" },
    ],
  },
  {
    slug: "knee-pain-physiotherapy",
    routePath: "/knee-pain",
    title: "Knee Pain Physiotherapy: Strength, Mobility and Function",
    shortTitle: "Knee Pain Physiotherapy",
    metaTitle: "Knee Pain Physiotherapy | Goswami Rehab",
    metaDescription: "Knee pain physiotherapy for mobility, strength, and daily function, with load progressed to the diagnosis. Share your goals and follow surgical guidance.",
    breadcrumbParent: "Pain & Mobility",
    summary: "Knee physiotherapy focuses on the combination of symptoms, strength, range of motion, balance, walking, and the activities you want to regain.",
    careContext: "Knee care is built around function: getting up from a chair, managing stairs, squatting, walking, or returning to exercise. Strength and load are progressed according to swelling, movement quality, and the relevant diagnosis.",
    covers: ["Knee osteoarthritis and activity-related pain", "Knee pain after a sprain, strain, or period of rest", "Difficulty with stairs, squatting, walking, or getting up", "Strength and balance loss after surgery or injury", "Return to work, exercise, or sport with appropriate clearance"],
    methods: ["Assessment of pain behaviour, swelling, range, strength, balance, gait, and task tolerance", "Progressive quadriceps, hip, calf, and whole-leg strengthening", "Mobility and movement practice for stairs, sit-to-stand, squatting, and walking", "Load management and pacing for work, exercise, and daily activities", "Coordination with the surgical or medical team when restrictions apply"],
    prognosis: "Knee symptoms can improve when load, strength, movement, and confidence are addressed together. Recovery depends on the diagnosis, irritability, swelling, medical history, and whether surgery or an acute injury is involved.",
    timeline: "A first assessment commonly takes 45–90 minutes. Strength and function often need 6–12 weeks of progressive practice, while post-operative and complex recovery continues according to healing and surgical milestones.",
    factors: ["Diagnosis and tissue-healing stage", "Swelling, range of motion, and quadriceps strength", "Walking pattern, balance, and confidence", "Exercise progression and recovery between sessions", "Weight-bearing or movement restrictions after surgery"],
    precautions: ["Urgent medical review may be needed for a hot, very swollen knee with fever, a locked knee after significant injury, sudden calf swelling, chest pain, or rapidly worsening function.", "Do not progress weight-bearing or resistance beyond surgical instructions.", "Pain during exercise should be interpreted with the overall response later that day and the next morning."],
    textbookBasis: "NICE NG226, Osteoarthritis in over 16s; Kisner & Colby, Therapeutic Exercise; Brukner & Khan’s Clinical Sports Medicine.",
    editorial: serviceGuideEditorial["knee-pain"],
    relatedLinks: [
      { href: "/blog/knee-osteoarthritis-physiotherapy-guide", label: "Read about exercise-based knee osteoarthritis physiotherapy" },
      { href: "/services/rehabilitation-programs", label: "Explore structured rehabilitation programmes" },
      { href: "/services/clinical-assessment-evaluation", label: "See what a physiotherapy assessment includes" },
    ],
  },
  {
    slug: "post-surgery-rehabilitation",
    routePath: "/post-surgery-rehab",
    title: "Post-Surgery Rehabilitation: Safe Recovery and Mobility",
    shortTitle: "Post-Surgery Rehabilitation",
    metaTitle: "Post-Surgery Rehabilitation | Goswami Rehab",
    metaDescription: "Post-surgery rehabilitation guided by your surgeon’s restrictions, healing, mobility, and function. Share discharge instructions before care is planned.",
    breadcrumbParent: "Rehabilitation",
    summary: "Post-surgery rehabilitation turns medical and surgical instructions into safe, measurable steps for mobility, strength, independence, and everyday function.",
    careContext: "This service starts with the operation and discharge instructions, then translates them into safe home tasks. Walking, transfers, stairs, wound precautions, caregiver support, and the home layout all affect the next milestone.",
    covers: ["Knee and hip replacement rehabilitation", "Recovery after orthopaedic or spinal surgery", "Mobility and transfer practice after hospital discharge", "Strength and conditioning after a period of inactivity", "Return to work and daily activities within medical restrictions"],
    methods: ["Review of the operation, discharge papers, precautions, medication, and current symptoms", "Assessment of walking, transfers, range, swelling, strength, balance, and confidence", "Early mobility, positioning, circulation, and symptom-management guidance", "Progressive strengthening, gait, stairs, endurance, and task practice", "Caregiver instruction and communication with the medical team when needed"],
    prognosis: "Recovery depends on the operation, healing, complications, baseline health, and participation. A physiotherapist can help measure functional progress, but cannot replace surgical review or guarantee a timeline.",
    timeline: "Early mobility starts according to the surgical plan. Many uncomplicated programmes progress over 6–16 weeks, while joint replacement, spinal, cancer, or complicated recovery may continue for several months.",
    factors: ["Surgical restrictions and tissue healing", "Pain, swelling, wound status, and range of motion", "Strength, balance, walking, and home layout", "Medical conditions and post-operative complications", "Sleep, nutrition, caregiver support, and home practice"],
    precautions: ["Follow the surgeon’s weight-bearing, movement, wound, and lifting instructions.", "Seek urgent medical review for fever, wound drainage, sudden swelling, severe calf pain, chest pain, new breathlessness, or sudden loss of function.", "Do not change medication, dressings, or surgical precautions based only on exercise advice."],
    textbookBasis: "O’Sullivan, Physical Rehabilitation; Kisner & Colby, Therapeutic Exercise; Braddom, Physical Medicine and Rehabilitation.",
    editorial: serviceGuideEditorial["post-surgery-rehab"],
    relatedLinks: [
      { href: "/services/rehabilitation-programs", label: "See structured rehabilitation programmes" },
      { href: "/blog/knee-replacement-recovery-guide", label: "Read the knee replacement recovery guide" },
      { href: "/blog/hip-replacement-homecare-physiotherapy", label: "Read about hip replacement home physiotherapy" },
    ],
  },
  {
    slug: "stroke-rehabilitation",
    routePath: "/stroke-rehab",
    title: "Stroke Rehabilitation at Home: Mobility and Independence",
    shortTitle: "Stroke Rehabilitation",
    metaTitle: "Stroke Rehabilitation at Home | Goswami Rehab",
    metaDescription: "Stroke rehabilitation for task practice, mobility, balance, arm function, and caregiver safety. Goals and progression depend on the clinical assessment.",
    breadcrumbParent: "Rehabilitation",
    summary: "Stroke rehabilitation at home is a personalised process that helps a person practise meaningful movement, transfers, balance, walking, and daily tasks as safely as possible.",
    careContext: "Stroke rehabilitation prioritises meaningful, repeatable tasks rather than isolated exercises alone. The therapist can work with the person and caregiver on bed mobility, transfers, walking, upper-limb use, fatigue, and falls prevention.",
    covers: ["Weakness, reduced control, or changes in walking after stroke", "Bed mobility, transfers, standing, and balance", "Upper-limb movement and task practice", "Fatigue, confidence, and safe activity progression", "Caregiver education and practical home adaptations"],
    methods: ["Review of the stroke history, medical stability, medication, communication, cognition, and goals", "Assessment of tone, strength, sensation, balance, transfers, gait, and functional tasks", "Repetitive, task-specific practice for meaningful daily activities", "Strength, endurance, balance, and walking progression scaled to fatigue and safety", "Caregiver coaching for positioning, transfers, falls prevention, and home practice"],
    prognosis: "Stroke recovery varies widely with the location and severity of the stroke, medical complications, cognition, fatigue, support, and time since onset. Progress is best tracked through meaningful function rather than a single symptom or test.",
    timeline: "Rehabilitation begins when medically appropriate and may continue for months or longer. Review frequency changes as safety, independence, and the person’s goals evolve.",
    factors: ["Stroke type, severity, and time since onset", "Strength, tone, sensation, balance, vision, speech, and cognition", "Fatigue, mood, sleep, and cardiovascular tolerance", "Home safety and caregiver availability", "Practice of meaningful tasks between sessions"],
    precautions: ["Sudden new weakness, facial droop, speech or vision change, severe headache, loss of balance, or confusion requires emergency stroke assessment.", "Exercise must be adapted for falls risk, fatigue, blood pressure, swallowing, and other medical needs.", "Caregivers should receive transfer instruction rather than lifting or pulling without training."],
    textbookBasis: "Winstein et al., Guidelines for Adult Stroke Rehabilitation and Recovery; Umphred’s Neurological Rehabilitation; O’Sullivan, Physical Rehabilitation.",
    editorial: serviceGuideEditorial["stroke-rehab"],
    relatedLinks: [
      { href: "/blog/stroke-rehabilitation-at-home", label: "Read the stroke rehabilitation at home guide" },
      { href: "/services/advanced-complex-case-recovery", label: "Explore complex case recovery" },
      { href: "/services/clinical-assessment-evaluation", label: "See the clinical assessment approach" },
    ],
  },
  {
    slug: "pain-management-physiotherapy",
    title: "Pain-Management Physiotherapy: Safer Movement and Recovery",
    shortTitle: "Pain-Management Physiotherapy",
    metaTitle: "Pain Management Physiotherapy | Goswami Rehab",
    metaDescription: "Pain-management physiotherapy for persistent pain, movement confidence, pacing, strength, and practical goals after assessment, without cure promises.",
    breadcrumbParent: "Pain & Mobility",
    summary: "Pain management physiotherapy helps make sense of symptoms and rebuild safe activity, strength, confidence, and participation without promising that every pain episode can be removed.",
    careContext: "The goal is a safer and more confident life with symptoms, not a promise of instant pain removal. The plan combines education, pacing, graded activity, strength, sleep and recovery factors, and referral when symptoms need another opinion.",
    covers: ["Persistent or recurring musculoskeletal pain", "Pain-related movement fear and reduced activity", "Back, neck, shoulder, knee, foot, or joint pain", "Deconditioning after illness, injury, or prolonged rest", "Practical pacing for work, sleep, exercise, and daily tasks"],
    methods: ["Assessment of symptoms, function, sleep, stress, health history, and goals", "Clear explanation of findings and factors that may influence pain", "Graded movement, strength, conditioning, and task exposure", "Pacing, flare-up planning, relaxation, and activity-modification strategies", "Referral or coordination with a doctor when symptoms do not fit a physiotherapy plan"],
    prognosis: "Persistent pain is real and can be influenced by tissues, the nervous system, sleep, stress, health, and context. Function and confidence can improve with a tailored programme, although symptom change is individual and not guaranteed.",
    timeline: "Early goals may be reviewed over 2–6 weeks. Building sustainable strength, activity tolerance, and confidence commonly takes several months with flexible progression.",
    factors: ["Pain irritability and duration", "Sleep, stress, mood, and recovery capacity", "Strength, conditioning, and movement confidence", "Work, caregiving, and activity demands", "Medical history and response to previous care"],
    precautions: ["Seek medical review for unexplained weight loss, fever, major trauma, progressive weakness, new neurological changes, a hot swollen joint, or severe unremitting pain.", "Pain is not a diagnosis by itself; persistent or changing symptoms need reassessment.", "A flare-up should lead to thoughtful adjustment, not forced exercise or complete avoidance of movement."],
    textbookBasis: "NICE NG193, Chronic pain; O’Sullivan, Physical Rehabilitation; International Association for the Study of Pain educational principles.",
    relatedLinks: [
      { href: "/back-pain", label: "Explore back pain physiotherapy" },
      { href: "/knee-pain", label: "Explore knee pain physiotherapy" },
      { href: "/services/clinical-assessment-evaluation", label: "Book a clinical assessment" },
    ],
  },
  {
    slug: "pregnancy-postpartum-support",
    title: "Pregnancy and Postpartum Support: Individualised Movement Guidance",
    shortTitle: "Pregnancy and Postpartum Support",
    metaTitle: "Pregnancy and Postpartum Support | Goswami Rehab",
    metaDescription: "Individualised physiotherapy, nutrition education, and exercise support during pregnancy and after birth, with appropriate maternity-team coordination.",
    breadcrumbParent: "Women's Health",
    summary: "An enquiry pathway for pregnancy and postpartum physiotherapy, general nutrition education, and exercise support shaped around your circumstances and goals.",
    careContext: "Activity and nutrition guidance is individualised. Complications, restrictions, concerning symptoms, or a need for medical review should be discussed with the appropriate maternity clinician before progressing.",
    covers: ["Movement and activity questions during pregnancy", "Postpartum return to everyday activity", "General nutrition education for rehabilitation and wellbeing", "Exercise support adapted to current tolerance", "Planning for referral or maternity-team coordination when needed"],
    methods: ["Review of goals, current activity, symptoms, medical advice, and relevant restrictions", "Functional movement and activity assessment within the clinician's scope", "Education about pacing, gradual progression, and symptom monitoring", "General nutrition and exercise education that does not replace medical nutrition therapy or maternity care", "Follow-up or referral when the presentation needs another clinician's review"],
    prognosis: "There is no fixed recovery timetable or universal activity prescription. The next step depends on symptoms, healing, medical guidance, goals, and how activity is tolerated.",
    timeline: "Review timing is individualised. A clinician can help decide when to reassess based on the person's goals, symptoms, and maternity-care plan.",
    factors: ["Stage of pregnancy or postpartum recovery", "Medical advice, restrictions, and symptom response", "Current strength, mobility, fatigue, and activity demands", "Sleep, nutrition, support, and recovery context", "Need for coordination with maternity or other healthcare professionals"],
    precautions: ["This educational service does not replace maternity, obstetric, or urgent medical care.", "Concerning or acute symptoms should be directed to the maternity team or local urgent medical service rather than a booking form.", "Do not begin a generic exercise or nutrition protocol when complications, restrictions, or significant symptoms need clinical review."],
    textbookBasis: "ACOG activity guidance; NICE postnatal and pelvic-floor guidance; WHO physical-activity guidance, interpreted conservatively and alongside individual clinical review.",
    relatedLinks: [
      { href: "/booking", label: "Request pregnancy or postpartum support" },
      { href: "/services/clinical-assessment-evaluation", label: "See the clinical assessment approach" },
    ],
  },
  {
    slug: "infant-early-development-physiotherapy",
    title: "Infant and Early-Development Physiotherapy Enquiry",
    shortTitle: "Infant and Early-Development Physiotherapy",
    metaTitle: "Infant and Early-Development Physiotherapy | Goswami Rehab",
    metaDescription: "A clinician-reviewed enquiry pathway for infant and early-development physiotherapy, with suitability and care coordination considered before booking.",
    breadcrumbParent: "Paediatric Rehabilitation",
    summary: "A pediatric-physiotherapist-led enquiry and assessment pathway for infants and young children, with suitability and clinician matching reviewed before care is planned.",
    careContext: "For preterm, medically complex, or very young infants, the child's pediatric or neonatal team may need to guide coordination. This enquiry does not provide newborn medical care or emergency triage.",
    covers: ["Infant and early-development movement concerns", "Questions about assessment suitability and clinician matching", "Caregiver education around everyday movement and handling within scope", "Review of goals, routines, and participation", "Coordination or referral when medical or specialist input is needed"],
    methods: ["Caregiver-led history of goals, routines, movement, and existing clinical guidance", "Age-appropriate observation and functional assessment when suitable", "Shared discussion of what can be addressed and what needs another professional", "Simple, individualised education for safe everyday participation", "Follow-up coordination with the child's existing healthcare team when appropriate"],
    prognosis: "Development and participation vary between children. The enquiry identifies suitable next steps rather than promising a diagnosis, developmental course, or particular outcome.",
    timeline: "Assessment and review timing depend on age, health, referral information, family goals, and clinician suitability review.",
    factors: ["Age, health, and developmental history", "Current medical advice and any restrictions", "Movement, play, routines, communication, and participation goals", "Caregiver priorities and available support", "Need for pediatric, neonatal, or other medical coordination"],
    precautions: ["This service is not NICU treatment, neonatal-specialist care, newborn medical care, or urgent pediatric assessment.", "Urgent or worrying symptoms should be taken to the child's pediatric team or local urgent medical service.", "Suitability and clinician matching are reviewed first; an enquiry is not a guarantee of an appointment or treatment plan."],
    textbookBasis: "NICE developmental follow-up guidance; WHO essential newborn-care principles; pediatric physiotherapy scope and referral principles.",
    relatedLinks: [
      { href: "/booking", label: "Request an infant or pediatric physiotherapy enquiry" },
      { href: "/services/pediatric-disability-rehabilitation", label: "Explore pediatric disability rehabilitation" },
    ],
  },
  {
    slug: "pediatric-disability-rehabilitation",
    title: "Physiotherapy for Children with Disabilities",
    shortTitle: "Pediatric Disability Rehabilitation",
    metaTitle: "Pediatric Disability Rehabilitation | Goswami Rehab",
    metaDescription: "Family-centred pediatric physiotherapy around movement, play, daily routines, and participation, with individual goals and caregiver support when needed.",
    breadcrumbParent: "Paediatric Rehabilitation",
    summary: "Family-centred physiotherapy for children with disabilities, with individual goals around movement, play, daily routines, and participation.",
    careContext: "Goals are developed with the child and caregivers and reviewed as needs change. Coordination or referral is part of responsible care when another professional or medical team is needed.",
    covers: ["Movement and participation goals", "Play, transfers, mobility, and daily routines", "Caregiver collaboration and practical home practice", "Individualised assessment and goal-setting", "Communication with the child's healthcare or education team when appropriate"],
    methods: ["Family-centred discussion of priorities, routines, environment, and participation", "Assessment of movement and functional tasks when suitable", "Play-based and task-focused practice adapted to the child's tolerance", "Caregiver education for safe, meaningful practice between visits", "Review, coordination, or referral when needs fall outside this service's scope"],
    prognosis: "Children have different strengths, needs, and contexts. Rehabilitation focuses on meaningful participation and shared goals without guaranteeing milestones, cure, independent walking, or another specific outcome.",
    timeline: "Review points are individualised and depend on the child's goals, response, routines, and coordination needs rather than a fixed programme length.",
    factors: ["Child and family priorities", "Movement, communication, learning, and participation context", "Medical guidance, fatigue, pain, and safety", "Home routines, equipment, and caregiver support", "Coordination with relevant healthcare, education, or community professionals"],
    precautions: ["This educational service does not replace pediatric or other medical care.", "Acute concerns or a rapid change in the child's health should go to the child's medical team or local urgent medical service.", "Goals and suitability are reviewed with the family; no milestone or availability outcome is guaranteed."],
    textbookBasis: "NICE cerebral-palsy guidance; WHO early-childhood development guidance; UNICEF inclusion and family-centred-care principles.",
    relatedLinks: [
      { href: "/booking", label: "Request pediatric disability rehabilitation" },
      { href: "/services/infant-early-development-physiotherapy", label: "Explore infant and early-development physiotherapy" },
    ],
  },
  {
    slug: "online-physiotherapy",
    routePath: "/online-physiotherapy",
    title: "Online Physiotherapy Consultation",
    shortTitle: "Online Physiotherapy",
    metaTitle: "Online Physiotherapy | Goswami Rehab",
    metaDescription: "Online physiotherapy consultation with movement guidance, exercise planning, and referral limits. Share your goals and ask whether remote care may fit.",
    breadcrumbParent: "Physiotherapy",
    summary: "Online physiotherapy can provide movement guidance, education, and rehabilitation planning when remote care is suitable for your needs.",
    careContext: "A video consultation does not replace an in-person examination or urgent medical assessment. A clinician may recommend another care setting if a remote review is not safe or sufficient.",
    covers: ["Movement and daily-activity questions", "Education and individualised exercise planning", "Rehabilitation follow-up between in-person appointments", "Functional goals that can be reviewed remotely", "Referral when a physical examination or other professional is needed"],
    methods: ["Review of symptoms, health history, goals, and current activity", "Visual movement assessment where appropriate and safe", "Guidance on pacing, exercises, and symptom monitoring", "Progress review using meaningful daily tasks", "Referral or coordination when remote care is not suitable"],
    prognosis: "Suitability and progress depend on the concern, health history, environment, and response. Online physiotherapy does not promise a diagnosis, outcome, or recovery date.",
    timeline: "Session length and follow-up are agreed after the initial discussion. The clinician may recommend in-person or medical review before further remote care.",
    factors: ["Nature and severity of symptoms", "Ability to communicate and move safely on video", "Home space, technology, and available support", "Medical advice and current restrictions", "Response to the agreed activity plan"],
    precautions: ["Seek urgent local care for chest pain, severe breathlessness, fainting, sudden neurological change, major trauma, or rapidly worsening weakness.", "Follow all post-surgery and weight-bearing restrictions.", "Stop an exercise that causes alarming symptoms and contact an appropriate clinician."],
    editorial: serviceGuideEditorial["online-physiotherapy"],
    relatedLinks: [
      { href: "/contact", label: "Request an online consultation" },
      { href: "/home-physiotherapy", label: "Explore home physiotherapy" },
    ],
  },
  {
    slug: "exercise-physiologist",
    routePath: "/exercise-physiologist",
    title: "Exercise Physiology for Safe, Goal-Led Activity",
    shortTitle: "Exercise Physiologist",
    metaTitle: "Exercise Physiologist | Goswami Rehab",
    metaDescription: "Exercise physiology for safe activity planning, strength, and endurance. Start with your health history and goals; medical clearance may be needed first.",
    breadcrumbParent: "Rehabilitation",
    summary: "Exercise physiology guidance helps match activity to your starting point, health context, and goals for daily function, recreation, or rehabilitation.",
    careContext: "Activity planning should account for symptoms and medical restrictions. The service does not diagnose heart, lung, metabolic, neurological, or musculoskeletal conditions.",
    covers: ["Activity and exercise planning", "Strength, endurance, mobility, and balance goals", "Gradual return to everyday or recreational tasks", "Recovery and symptom-monitoring strategies", "Referral or medical coordination when needed"],
    methods: ["Review of health history, medicines, activity, symptoms, and goals", "Functional movement and exertion discussion when appropriate", "Gradual planning for duration, frequency, resistance, or task complexity", "Review of symptom response during and after activity", "Referral for medical clearance when the situation requires it"],
    prognosis: "The plan and response vary with health, baseline capacity, consistency, and recovery. No fitness, weight, or performance result is guaranteed.",
    timeline: "Progress and review intervals are based on the person’s goals and response, not a fixed programme length. Significant symptoms may require medical review first.",
    factors: ["Current health and medical advice", "Symptoms such as dizziness, chest discomfort, or unusual breathlessness", "Starting activity level and recovery capacity", "Daily demands and personal goals", "Ability to practise safely and consistently"],
    precautions: ["Seek urgent care for chest pressure, severe breathlessness, fainting, collapse, or a sudden neurological change.", "Do not replace medical advice with an online exercise target.", "Ask about medical clearance after significant illness, surgery, or a change in symptoms."],
    editorial: serviceGuideEditorial["exercise-physiologist"],
    relatedLinks: [
      { href: "/contact", label: "Ask about exercise physiology" },
      { href: "/services/clinical-assessment-evaluation", label: "Explore clinical assessment" },
    ],
  },
  {
    slug: "neck-pain",
    routePath: "/neck-pain",
    title: "Neck Pain Physiotherapy: Movement and Function",
    shortTitle: "Neck Pain Physiotherapy",
    metaTitle: "Neck Pain Physiotherapy | Goswami Rehab",
    metaDescription: "Neck pain physiotherapy for movement, strength, and activity guidance, with warning-sign screening. New weakness or severe symptoms need clinician review.",
    breadcrumbParent: "Physiotherapy",
    summary: "Neck pain physiotherapy begins with a careful history and functional assessment, then considers movement, strength, and activity goals where appropriate.",
    careContext: "Neck symptoms have different causes and may need medical assessment. A general webpage cannot diagnose the source or determine whether a particular exercise is suitable.",
    covers: ["Neck movement and daily-task limitations", "Work, sleep, and activity-related questions", "Progressive strength and movement options", "Pacing and self-management education", "Referral when symptoms suggest another assessment is needed"],
    methods: ["Review of symptom onset, medical history, function, and goals", "Assessment of movement and relevant neurological signs as appropriate", "Individual guidance on activity, exercise, and symptom monitoring", "Progress review based on function and tolerance", "Coordination with a doctor when findings or symptoms need review"],
    prognosis: "Neck pain varies in cause and duration. Progress depends on the underlying condition, health context, and response to care; a particular result or timeline is not guaranteed.",
    timeline: "Review timing follows the assessment and response. Persistent, worsening, or unusual symptoms should be reconsidered by an appropriate clinician.",
    factors: ["Onset, duration, and behaviour of symptoms", "Arm pain, numbness, weakness, or coordination changes", "Work and daily activity demands", "Medical history and previous episodes", "Response to movement and agreed activity"],
    precautions: ["Seek urgent care after significant trauma or for new weakness, trouble walking, loss of coordination, severe headache, fever with neck stiffness, or sudden neurological symptoms.", "Do not force painful movement or use a generic routine as a diagnosis.", "Discuss persistent or worsening symptoms with a clinician."],
    editorial: serviceGuideEditorial["neck-pain"],
    relatedLinks: [
      { href: "/contact", label: "Request a neck pain consultation" },
      { href: "/back-pain", label: "Explore back pain physiotherapy" },
    ],
  },
  {
    slug: "sciatica",
    routePath: "/sciatica",
    title: "Sciatica Physiotherapy and Leg Symptom Assessment",
    shortTitle: "Sciatica Physiotherapy",
    metaTitle: "Sciatica Physiotherapy | Goswami Rehab",
    metaDescription: "Sciatica care starts with symptom and nerve screening, then graded activity as indicated. New bladder or bowel changes or severe weakness need urgent care.",
    breadcrumbParent: "Physiotherapy",
    summary: "Sciatica-related leg symptoms need a history and safety screen before a clinician considers movement, activity, or rehabilitation guidance.",
    careContext: "Leg pain, tingling, or numbness can have different causes. Physiotherapy education is not a diagnosis, and some symptoms need urgent medical assessment.",
    covers: ["Leg pain, tingling, or numbness affecting function", "Movement and activity tolerance", "Education on pacing and symptom monitoring", "Progressive activity when suitable", "Referral for medical or in-person review when needed"],
    methods: ["Review of symptom pattern, strength, sensation, and health history", "Screening for urgent warning signs", "Functional movement and activity assessment where appropriate", "Individual guidance on graded activity and follow-up", "Referral if symptoms or examination require medical review"],
    prognosis: "Symptoms can change over time and their course depends on the cause and individual health factors. No particular outcome or recovery date can be promised.",
    timeline: "The assessment determines whether physiotherapy is appropriate and when to review. New or worsening neurological symptoms need timely medical attention.",
    factors: ["Symptom distribution and progression", "Strength, sensation, and walking function", "Medical history and other health conditions", "Activity response and daily demands", "Whether medical imaging or another clinician’s assessment is indicated"],
    precautions: ["Seek emergency care for new loss of bladder or bowel control, numbness around the saddle area, or rapidly worsening leg weakness.", "Seek prompt medical review for progressive numbness, fever, significant trauma, or severe unexplained symptoms.", "Do not delay urgent assessment to try online exercises."],
    editorial: serviceGuideEditorial.sciatica,
    relatedLinks: [
      { href: "/contact", label: "Request a sciatica consultation" },
      { href: "/back-pain", label: "Explore back pain physiotherapy" },
    ],
  },
  {
    slug: "arthritis-osteoarthritis",
    routePath: "/arthritis-osteoarthritis",
    title: "Arthritis and Osteoarthritis Physiotherapy",
    shortTitle: "Arthritis & Osteoarthritis",
    metaTitle: "Arthritis Physiotherapy | Goswami Rehab",
    metaDescription: "Physiotherapy for arthritis and osteoarthritis with strength, mobility, pacing, and function goals. Care varies by joint, symptoms, and clinical review.",
    breadcrumbParent: "Physiotherapy",
    summary: "Physiotherapy for arthritis and osteoarthritis can focus on strength, mobility, activity, and daily function alongside appropriate medical care.",
    careContext: "Arthritis includes different conditions. Joint symptoms should not be self-diagnosed from a webpage, and medical treatment decisions remain with the relevant healthcare professional.",
    covers: ["Joint movement and daily activities", "Strength, balance, and walking goals", "Pacing and activity planning", "Education about exercise and symptom response", "Referral when a joint or systemic symptom needs medical review"],
    methods: ["Review of diagnosis, symptoms, medical advice, and priorities", "Assessment of movement and functional tasks as appropriate", "Individual strength, mobility, and activity guidance", "Progress review based on function and tolerance", "Coordination with a doctor or rheumatology team when useful"],
    prognosis: "Function and symptoms vary by arthritis type, joint, health, and treatment. Exercise can be part of care but does not cure arthritis or guarantee a specific outcome.",
    timeline: "Progress is reviewed over time and adjusted to the joint, health context, and response. A new hot or markedly swollen joint may require prompt medical review.",
    factors: ["Type of arthritis and affected joint", "Pain, swelling, stiffness, and function", "Medical treatment and other health conditions", "Activity level, sleep, and recovery", "Personal goals and support"],
    precautions: ["Seek medical advice for a new hot swollen joint, fever, sudden severe pain, or a rapid change in function.", "Follow advice about medication and medical treatment; do not change it based on exercise guidance.", "Use a comfortable, individually assessed level of activity rather than forcing painful movement."],
    editorial: serviceGuideEditorial["arthritis-osteoarthritis"],
    relatedLinks: [
      { href: "/contact", label: "Ask about arthritis physiotherapy" },
      { href: "/knee-pain", label: "Explore knee pain physiotherapy" },
    ],
  },
  {
    slug: "parkinsons-rehab",
    routePath: "/parkinsons-rehab",
    title: "Parkinson’s Rehabilitation for Mobility and Daily Life",
    shortTitle: "Parkinson’s Rehabilitation",
    metaTitle: "Parkinson’s Rehabilitation | Goswami Rehab",
    metaDescription: "Parkinson’s rehabilitation focused on mobility, balance, transfers, cueing, and daily function. Plans adapt to symptoms, falls risk, and medical advice.",
    breadcrumbParent: "Neurological Rehabilitation",
    summary: "Parkinson’s rehabilitation can address mobility, balance, transfers, and participation through individual goals and coordination with the person’s healthcare team.",
    careContext: "Parkinson’s affects people differently and may involve medication timing, fatigue, cognition, and falls risk. Rehabilitation does not replace neurological or medical care.",
    covers: ["Walking, turning, and transfer goals", "Balance and falls-prevention questions", "Movement strategies and cueing where appropriate", "Daily activity and caregiver education", "Coordination with the treating neurologist or other clinicians"],
    methods: ["Review of movement, falls, daily function, medication context, and goals", "Assessment of relevant tasks in a safe environment", "Individual practice for mobility, balance, strength, and task performance", "Education about safe activity and when to seek review", "Follow-up and care coordination with consent"],
    prognosis: "Parkinson’s is a variable neurological condition. Rehabilitation can support function and participation but does not cure the condition or guarantee a particular level of independence.",
    timeline: "Goals and review intervals are individualised and may change with symptoms, medication, health, and daily support needs.",
    factors: ["Movement symptoms and day-to-day variation", "Falls history, balance, and walking environment", "Medication plan and medical advice", "Cognition, fatigue, sleep, and other health conditions", "Personal goals and caregiver support"],
    precautions: ["Seek urgent care for a sudden neurological change, serious fall, head injury, chest pain, or collapse.", "Report increasing falls, freezing, swallowing difficulty, or medication-related concerns to the treating team.", "Do not alter Parkinson’s medication because of exercise advice."],
    editorial: serviceGuideEditorial["parkinsons-rehab"],
    relatedLinks: [
      { href: "/contact", label: "Ask about Parkinson’s rehabilitation" },
      { href: "/stroke-rehab", label: "Explore stroke rehabilitation" },
    ],
  },
  {
    slug: "weight-management",
    routePath: "/weight-management",
    title: "Weight Management Support with Practical Health Goals",
    shortTitle: "Weight Management",
    metaTitle: "Weight Management Support | Goswami Rehab",
    metaDescription: "Weight management support with practical nutrition and movement goals, adapted to health needs and preferences. No plan or weight outcome is guaranteed.",
    breadcrumbParent: "Nutrition",
    summary: "Weight-management support can help set practical food and activity goals without shame, rigid promises, or assumptions based on body size.",
    careContext: "Weight is influenced by health, medicines, sleep, stress, access to food, and many other factors. Complex medical or eating-related needs may require a registered dietitian or doctor.",
    covers: ["Personal health and daily-routine goals", "Practical food and activity planning", "Movement goals adapted to function and health", "Review of barriers and sustainable habits", "Referral when specialist medical or nutrition care is needed"],
    methods: ["Discussion of priorities, health history, medicines, and daily routine", "Collaborative goal-setting based on preference and access", "Practical nutrition and movement education within scope", "Review of wellbeing, function, and sustainability", "Coordination with a registered dietitian or doctor when required"],
    prognosis: "There is no single expected rate or amount of weight change. Any plan should be safe, sustainable, and directed toward the person’s goals and health needs.",
    timeline: "Review timing depends on the agreed goal and clinical context. Ongoing support should adapt when symptoms, health, access, or priorities change.",
    factors: ["Medical conditions and medicines", "Food access, culture, and budget", "Sleep, stress, appetite, and activity", "Pain, fatigue, mobility, and other functional needs", "Personal goals and available clinical support"],
    precautions: ["Avoid crash diets, unverified supplements, or exercise plans that conflict with medical advice.", "People with diabetes, kidney or heart disease, pregnancy, or eating-related concerns may need specialist care.", "Seek medical review for unintentional weight change or persistent symptoms."],
    editorial: serviceGuideEditorial["weight-management"],
    relatedLinks: [
      { href: "/contact", label: "Ask about weight-management support" },
      { href: "/nutritionist-dietitian-online", label: "Explore online nutrition consultation" },
    ],
  },
];

export const serviceGuideBySlug = Object.fromEntries(
  serviceGuides.map((guide) => [guide.slug, guide]),
) as Record<string, ServiceGuide>;

export const serviceGuideByPath = Object.fromEntries(
  serviceGuides.map((guide) => [guide.routePath ?? `/services/${guide.slug}`, guide]),
) as Record<string, ServiceGuide>;