// Generated by scripts/generate-client-data.ts. Do not edit by hand.

export const services = [
  {
    "id": "physio-session",
    "title": "Homecare Physiotherapy",
    "description": "Expert one-on-one physiotherapy at your home in 45 listed cities for pain relief, injury recovery, and restoring full movement. Exact-locality and clinician availability are confirmed before visits."
  },
  {
    "id": "cardiopulmonary-rehab",
    "title": "Cardiopulmonary Rehabilitation",
    "description": "Specialised breathing, cardiac, and pulmonary rehabilitation for COPD, post-bypass recovery, heart failure, and respiratory conditions — delivered at home."
  },
  {
    "id": "advanced-complex-recovery",
    "title": "Advanced Complex Case Recovery",
    "description": "Comprehensive rehabilitation for complex neurological, multi-system, and post-ICU cases. Expert physiotherapy support for stroke rehabilitation, brain injury rehabilitation, Guillain-Barré rehabilitation, and spinal rehabilitation."
  },
  {
    "id": "assessment-protocols",
    "title": "Clinical Assessment & Evaluation",
    "description": "Standardised physiotherapy assessments including functional movement screening, neurological evaluation, musculoskeletal grading, and outcome tracking."
  },
  {
    "id": "sports-enhancement",
    "title": "Sports Enhancement Consultation",
    "description": "Optimise your athletic performance through biomechanical analysis, movement screening, and sport-specific conditioning programs."
  },
  {
    "id": "functional-training",
    "title": "Functional Training",
    "description": "Build strength and movement patterns that carry over to everyday life and sport. Train the way your body is designed to move."
  },
  {
    "id": "nutritional-consultation",
    "title": "Nutritional Consultation",
    "description": "Fuel your recovery and performance with personalised nutrition guidance aligned with your rehabilitation and training goals."
  },
  {
    "id": "general-consultation",
    "title": "General Consultation",
    "description": "Not sure where to start? A comprehensive initial assessment to understand your condition and map out the right path forward."
  },
  {
    "id": "rehabilitation",
    "title": "Rehabilitation Programs",
    "description": "Structured, progressive physiotherapy rehabilitation programmes for post-surgery and injury recovery — designed around safe mobility, strength, and everyday function."
  },
  {
    "id": "pregnancy-postpartum-support",
    "title": "Pregnancy and Postpartum Support",
    "description": "Individualised physiotherapy, general nutrition education, and exercise support during pregnancy and after birth, with appropriate clinical coordination."
  },
  {
    "id": "infant-early-development-physiotherapy",
    "title": "Infant and Early-Development Physiotherapy Enquiry",
    "description": "A clinician-reviewed enquiry pathway for infant and early-development physiotherapy, with suitability and matching considered first."
  },
  {
    "id": "pediatric-disability-rehabilitation",
    "title": "Pediatric Disability Rehabilitation",
    "description": "Family-centred physiotherapy around movement, play, daily routines, and participation, with individual goals and coordination."
  }
] as const;

export const appointmentTypes = [
  "General Consultation",
  "Clinical Assessment & Evaluation",
  "Homecare Physiotherapy Session",
  "Cardiopulmonary Rehabilitation",
  "Advanced Complex Case Recovery",
  "Sports Enhancement Consultation",
  "Nutritional Consultation",
  "Rehabilitation Program",
  "Antenatal/postpartum physiotherapy",
  "Pregnancy/postpartum nutrition support",
  "Pregnancy/postpartum exercise support",
  "Infant/pediatric physiotherapy enquiry",
  "Pediatric disability rehabilitation"
] as const;

export const telehealthAppointmentTypes = [
  "Telehealth — Initial Assessment",
  "Telehealth — Follow-up Consultation",
  "Telehealth — Exercise Programme Review",
  "Telehealth — Post-Surgery Guidance",
  "Telehealth — Second Opinion / Case Review",
  "Antenatal/postpartum physiotherapy",
  "Pregnancy/postpartum nutrition support",
  "Pregnancy/postpartum exercise support",
  "Infant/pediatric physiotherapy enquiry",
  "Pediatric disability rehabilitation"
] as const;
