// Generated by scripts/generate-client-data.ts. Do not edit by hand.
import type { StateJournalPostSummary } from "./state-journal-index";

export const stateJournalIndex = [
  {
    "slug": "stroke-rehabilitation-safer-home-practice-chandigarh",
    "title": "Stroke Rehabilitation in Chandigarh: From Cli…",
    "citySlug": "chandigarh",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-support-during-rehabilitation-chandigarh",
    "title": "Nutrition Support During Rehabilitation in Ch…",
    "citySlug": "chandigarh",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-monitoring-rehabilitation-chandigarh",
    "title": "Exercise Monitoring in Chandigarh Rehabilitat…",
    "citySlug": "chandigarh",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-physiotherapy-assessment-home-ahmedabad",
    "title": "After a Stroke in Ahmedabad: How Physiotherap…",
    "citySlug": "ahmedabad",
    "discipline": "physiotherapy"
  },
  {
    "slug": "eating-for-rehabilitation-and-training-ahmedabad",
    "title": "Eating for Rehabilitation and Training in Ahm…",
    "citySlug": "ahmedabad",
    "discipline": "nutrition"
  },
  {
    "slug": "cardiac-orthopaedic-rehabilitation-exercise-ahmedabad",
    "title": "Building Exercise Safely in Cardiac and Ortho…",
    "citySlug": "ahmedabad",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-rehabilitation-home-practical-progress-lucknow",
    "title": "Stroke Rehabilitation at Home in Lucknow: Fro…",
    "citySlug": "lucknow",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-post-surgery-recovery-lucknow",
    "title": "Nutrition as Part of Post-Surgery Recovery in…",
    "citySlug": "lucknow",
    "discipline": "nutrition"
  },
  {
    "slug": "cardiopulmonary-joint-replacement-exercise-lucknow",
    "title": "A Safer Exercise Plan for Cardiopulmonary and…",
    "citySlug": "lucknow",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "neurological-fatigue-pacing-household-tasks-mumbai",
    "title": "Neurological Fatigue Physiotherapy in Mumbai:…",
    "citySlug": "mumbai",
    "discipline": "physiotherapy"
  },
  {
    "slug": "cardiac-rehabilitation-nutrition-appetite-medicines-mumbai",
    "title": "Eating During Cardiac Rehabilitation in Mumba…",
    "citySlug": "mumbai",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-after-guillain-barre-fatigue-mumbai",
    "title": "Exercise After Guillain–Barré in Mumbai: Moni…",
    "citySlug": "mumbai",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "post-surgery-stairs-community-mobility-pune",
    "title": "Post-Surgery Physiotherapy for Stairs and Com…",
    "citySlug": "pune",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-pulmonary-rehabilitation-appetite-breathlessness-pune",
    "title": "Nutrition During Pulmonary Rehabilitation in…",
    "citySlug": "pune",
    "discipline": "nutrition"
  },
  {
    "slug": "cross-training-after-sports-injury-pune",
    "title": "Cross-Training After Sports Injury in Pune: M…",
    "citySlug": "pune",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "upper-limb-task-retraining-after-stroke-hyderabad",
    "title": "Upper-Limb Physiotherapy After Stroke in Hyde…",
    "citySlug": "hyderabad",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-when-cardiopulmonary-illness-makes-eating-tiring-hyderabad",
    "title": "When Cardiopulmonary Illness Makes Eating Tir…",
    "citySlug": "hyderabad",
    "discipline": "nutrition"
  },
  {
    "slug": "post-discharge-exercise-monitoring-neurological-cardiac-hyderabad",
    "title": "After Hospital Discharge in Hyderabad: Sympto…",
    "citySlug": "hyderabad",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "spinal-surgery-bed-mobility-transfers-noida",
    "title": "Spinal Surgery Physiotherapy in Noida: Bed Mo…",
    "citySlug": "noida",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-after-spine-surgery-constipation-noida",
    "title": "Nutrition After Spine Surgery in Noida: Appet…",
    "citySlug": "noida",
    "discipline": "nutrition"
  },
  {
    "slug": "copd-exercise-breathlessness-monitoring-noida",
    "title": "Exercising With COPD in Noida: Using Breathle…",
    "citySlug": "noida",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "dual-task-walking-neurological-rehabilitation-amritsar",
    "title": "Dual-Task Walking Physiotherapy in Amritsar:…",
    "citySlug": "amritsar",
    "discipline": "physiotherapy"
  },
  {
    "slug": "older-adult-nutrition-appetite-muscle-rehabilitation-amritsar",
    "title": "Nutrition for Older Adults in Amritsar Rehabi…",
    "citySlug": "amritsar",
    "discipline": "nutrition"
  },
  {
    "slug": "frailty-exercise-strength-sit-to-stand-amritsar",
    "title": "Frailty Exercise in Amritsar: Building Streng…",
    "citySlug": "amritsar",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "shoulder-preservation-physiotherapy-spinal-cord-injury-ludhiana",
    "title": "Shoulder-Preserving Physiotherapy After Spina…",
    "citySlug": "ludhiana",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-spinal-cord-injury-bowel-skin-ludhiana",
    "title": "Nutrition After Spinal Cord Injury in Ludhian…",
    "citySlug": "ludhiana",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-after-spinal-cord-injury-autonomic-monitoring-ludhiana",
    "title": "Exercise After Spinal Cord Injury in Ludhiana…",
    "citySlug": "ludhiana",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "foot-drop-home-walking-kochi",
    "title": "Foot Drop Physiotherapy at Home in Kochi: Toe…",
    "citySlug": "kochi",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-pressure-injury-prevention-kochi",
    "title": "Nutrition and Pressure-Injury Prevention Duri…",
    "citySlug": "kochi",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-frailty-strength-kochi",
    "title": "Exercise Physiology for Frailty in Kochi: Bui…",
    "citySlug": "kochi",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "parkinsons-freezing-turning-home-physiotherapy-thiruvananthapuram",
    "title": "Parkinson's Freezing and Turning in Thiruvana…",
    "citySlug": "thiruvananthapuram",
    "discipline": "physiotherapy"
  },
  {
    "slug": "parkinsons-rehabilitation-nutrition-appetite-swallowing-medicines-thiruvananthapuram",
    "title": "Nutrition Questions in Parkinson's Rehabilita…",
    "citySlug": "thiruvananthapuram",
    "discipline": "nutrition"
  },
  {
    "slug": "dual-task-exercise-parkinsons-rehabilitation-thiruvananthapuram",
    "title": "Dual-Task Exercise in Parkinson's Rehabilitat…",
    "citySlug": "thiruvananthapuram",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "copd-physiotherapy-everyday-tasks-kozhikode",
    "title": "COPD Physiotherapy in Kozhikode: Making Every…",
    "citySlug": "kozhikode",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-risk-geriatric-rehabilitation-kozhikode",
    "title": "Nutrition Risk During Geriatric Rehabilitatio…",
    "citySlug": "kozhikode",
    "discipline": "nutrition"
  },
  {
    "slug": "prehabilitation-exercise-before-surgery-kozhikode",
    "title": "Prehabilitation Exercise Before Surgery in Ko…",
    "citySlug": "kozhikode",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "guillain-barre-physiotherapy-overwork-weakness-visakhapatnam",
    "title": "Guillain-Barré Physiotherapy in Visakhapatnam…",
    "citySlug": "visakhapatnam",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-swallowing-after-guillain-barre-visakhapatnam",
    "title": "Nutrition and Swallowing Questions After Guil…",
    "citySlug": "visakhapatnam",
    "discipline": "nutrition"
  },
  {
    "slug": "breathing-focused-exercise-after-guillain-barre-visakhapatnam",
    "title": "Breathing-Focused Exercise After Guillain-Bar…",
    "citySlug": "visakhapatnam",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "older-adult-deconditioning-home-physiotherapy-nagpur",
    "title": "After Hospitalisation in Nagpur: Home Physiot…",
    "citySlug": "nagpur",
    "discipline": "physiotherapy"
  },
  {
    "slug": "older-adult-rehabilitation-nutrition-chewing-swallowing-nagpur",
    "title": "Nutrition Questions for Older-Adult Rehabilit…",
    "citySlug": "nagpur",
    "discipline": "nutrition"
  },
  {
    "slug": "aerobic-exercise-after-stroke-nagpur",
    "title": "Aerobic Exercise After Stroke in Nagpur: Buil…",
    "citySlug": "nagpur",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "visual-scanning-safe-route-finding-after-stroke-guwahati",
    "title": "After Stroke in Guwahati: Visual Scanning and…",
    "citySlug": "guwahati",
    "discipline": "physiotherapy"
  },
  {
    "slug": "neurological-meal-fatigue-swallowing-uncertainty-guwahati",
    "title": "Neurological Rehabilitation in Guwahati: When…",
    "citySlug": "guwahati",
    "discipline": "nutrition"
  },
  {
    "slug": "orthostatic-symptoms-early-return-home-guwahati",
    "title": "Early Return Home in Guwahati: Monitoring Ort…",
    "citySlug": "guwahati",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "bed-to-bathroom-sequencing-cardiac-thoracic-surgery-kolkata",
    "title": "After Cardiac or Thoracic Surgery in Kolkata:…",
    "citySlug": "kolkata",
    "discipline": "physiotherapy"
  },
  {
    "slug": "record-before-changing-food-fluids-cardiopulmonary-meal-exhaustion-kolkata",
    "title": "When Cardiopulmonary Recovery Makes Meals Exh…",
    "citySlug": "kolkata",
    "discipline": "nutrition"
  },
  {
    "slug": "cardiopulmonary-recovery-log-after-discharge-kolkata",
    "title": "After Cardiopulmonary Discharge in Kolkata: A…",
    "citySlug": "kolkata",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-telerehabilitation-caregiver-coaching-chennai",
    "title": "Stroke Telerehabilitation in Chennai: Caregiv…",
    "citySlug": "chennai",
    "discipline": "physiotherapy"
  },
  {
    "slug": "preoperative-nutrition-screening-knee-replacement-chennai",
    "title": "Before Knee Replacement in Chennai: Nutrition…",
    "citySlug": "chennai",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-assessment-after-critical-illness-chennai",
    "title": "After Critical Illness in Chennai: Separating…",
    "citySlug": "chennai",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "copd-airway-clearance-physiotherapy-coimbatore",
    "title": "COPD Airway-Clearance Physiotherapy in Coimba…",
    "citySlug": "coimbatore",
    "discipline": "physiotherapy"
  },
  {
    "slug": "diabetes-kidney-rehabilitation-nutrition-questions-coimbatore",
    "title": "Nutrition Questions When Diabetes or Kidney R…",
    "citySlug": "coimbatore",
    "discipline": "nutrition"
  },
  {
    "slug": "copd-exercise-physiology-heat-pacing-coimbatore",
    "title": "COPD Exercise Physiology in Coimbatore: Heat-…",
    "citySlug": "coimbatore",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "orthopaedic-surgery-bathing-dressing-home-routines-madurai",
    "title": "After Orthopaedic Surgery in Madurai: Bathing…",
    "citySlug": "madurai",
    "discipline": "physiotherapy"
  },
  {
    "slug": "geriatric-rehabilitation-appetite-chewing-weight-questions-madurai",
    "title": "Geriatric Rehabilitation in Madurai: Appetite…",
    "citySlug": "madurai",
    "discipline": "nutrition"
  },
  {
    "slug": "walking-readiness-after-hospitalisation-madurai",
    "title": "Walking Readiness After Hospitalisation in Ma…",
    "citySlug": "madurai",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-dressing-reaching-home-practice-mysuru",
    "title": "Stroke Rehabilitation in Mysuru: Rebuilding D…",
    "citySlug": "mysuru",
    "discipline": "physiotherapy"
  },
  {
    "slug": "parkinsons-constipation-appetite-meal-questions-mysuru",
    "title": "Parkinson’s Rehabilitation in Mysuru: Constip…",
    "citySlug": "mysuru",
    "discipline": "nutrition"
  },
  {
    "slug": "parkinsons-exercise-movement-variability-mysuru",
    "title": "Parkinson’s Exercise in Mysuru: What to Revie…",
    "citySlug": "mysuru",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "copd-pacing-bathing-meal-preparation-mangaluru",
    "title": "COPD Physiotherapy in Mangaluru: Pacing Bathi…",
    "citySlug": "mangaluru",
    "discipline": "physiotherapy"
  },
  {
    "slug": "pulmonary-rehabilitation-meal-fatigue-weight-change-mangaluru",
    "title": "Pulmonary Rehab in Mangaluru: Meal Fatigue an…",
    "citySlug": "mangaluru",
    "discipline": "nutrition"
  },
  {
    "slug": "copd-exercise-cough-sputum-recovery-mangaluru",
    "title": "COPD Exercise in Mangaluru: Cough, Sputum, an…",
    "citySlug": "mangaluru",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "knee-replacement-vehicle-transfers-community-mobility-surat",
    "title": "Knee Replacement Rehabilitation in Surat: Veh…",
    "citySlug": "surat",
    "discipline": "physiotherapy"
  },
  {
    "slug": "knee-replacement-nutrition-diabetes-kidney-questions-surat",
    "title": "Knee Replacement in Surat: Nutrition Question…",
    "citySlug": "surat",
    "discipline": "nutrition"
  },
  {
    "slug": "knee-replacement-swelling-load-tolerance-exercise-surat",
    "title": "After Knee Replacement in Surat: Monitoring S…",
    "citySlug": "surat",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "orthopaedic-recovery-reaching-carrying-vadodara",
    "title": "Orthopaedic Recovery in Vadodara: Safer Reach…",
    "citySlug": "vadodara",
    "discipline": "physiotherapy"
  },
  {
    "slug": "stroke-meal-setup-one-sided-weakness-vadodara",
    "title": "Nutrition After Stroke in Vadodara: Safer Mea…",
    "citySlug": "vadodara",
    "discipline": "nutrition"
  },
  {
    "slug": "geriatric-exercise-household-endurance-vadodara",
    "title": "Geriatric Exercise in Vadodara: Building Hous…",
    "citySlug": "vadodara",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "neurological-walking-thresholds-home-routes-kanpur",
    "title": "Neurological Walking in Kanpur: Safer Home Ro…",
    "citySlug": "kanpur",
    "discipline": "physiotherapy"
  },
  {
    "slug": "post-surgery-appetite-constipation-intake-kanpur",
    "title": "After Surgery in Kanpur: Appetite, Constipati…",
    "citySlug": "kanpur",
    "discipline": "nutrition"
  },
  {
    "slug": "copd-exercise-recovery-after-short-tasks-kanpur",
    "title": "COPD Exercise in Kanpur: Recovery After Short…",
    "citySlug": "kanpur",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-bathroom-sequencing-home-physiotherapy-varanasi",
    "title": "Stroke Rehabilitation in Varanasi: Safer Bath…",
    "citySlug": "varanasi",
    "discipline": "physiotherapy"
  },
  {
    "slug": "geriatric-hydration-meal-routines-varanasi",
    "title": "Geriatric Nutrition in Varanasi: Hydration an…",
    "citySlug": "varanasi",
    "discipline": "nutrition"
  },
  {
    "slug": "copd-exercise-meaningful-household-route-varanasi",
    "title": "COPD Exercise in Varanasi: A Meaningful Home…",
    "citySlug": "varanasi",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "knee-replacement-stairs-thresholds-bhopal",
    "title": "Knee Replacement in Bhopal: Safer Stairs and…",
    "citySlug": "bhopal",
    "discipline": "physiotherapy"
  },
  {
    "slug": "knee-replacement-nutrition-shopping-cooking-bhopal",
    "title": "Knee Replacement in Bhopal: Nutrition and Mea…",
    "citySlug": "bhopal",
    "discipline": "nutrition"
  },
  {
    "slug": "copd-exercise-symptoms-pacing-recovery-bhopal",
    "title": "COPD Exercise in Bhopal: Symptoms, Pacing, an…",
    "citySlug": "bhopal",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "post-surgery-car-transfers-home-agra",
    "title": "After Surgery in Agra: Safer Car Transfers an…",
    "citySlug": "agra",
    "discipline": "physiotherapy"
  },
  {
    "slug": "recovery-nutrition-appetite-meal-participation-agra",
    "title": "Recovery Nutrition in Agra: Appetite and Meal…",
    "citySlug": "agra",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-physiology-travel-day-recovery-agra",
    "title": "Exercise Physiology in Agra: Preparing for a…",
    "citySlug": "agra",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-dressing-cueing-one-sided-task-prayagraj",
    "title": "After Stroke in Prayagraj: Dressing, Cueing,…",
    "citySlug": "prayagraj",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-meal-tolerance-breathlessness-fatigue-prayagraj",
    "title": "Nutrition in Prayagraj: When Breathlessness I…",
    "citySlug": "prayagraj",
    "discipline": "nutrition"
  },
  {
    "slug": "short-bout-neurological-conditioning-prayagraj",
    "title": "Neurological Exercise in Prayagraj: Building…",
    "citySlug": "prayagraj",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "post-surgery-bed-chair-transfers-jodhpur",
    "title": "After Surgery in Jodhpur: Bed-to-Chair Transf…",
    "citySlug": "jodhpur",
    "discipline": "physiotherapy"
  },
  {
    "slug": "nutrition-recovery-meal-timing-symptoms-jodhpur",
    "title": "Nutrition and Recovery in Jodhpur: When Meal…",
    "citySlug": "jodhpur",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-physiology-home-space-energy-jodhpur",
    "title": "Exercise Physiology in Jodhpur: Adapting Prac…",
    "citySlug": "jodhpur",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "caregiver-supported-transfers-hand-placement-udaipur",
    "title": "Caregiver-Supported Transfers in Udaipur: Saf…",
    "citySlug": "udaipur",
    "discipline": "physiotherapy"
  },
  {
    "slug": "geriatric-nutrition-meal-access-chewing-udaipur",
    "title": "Geriatric Nutrition in Udaipur: Meal Access a…",
    "citySlug": "udaipur",
    "discipline": "nutrition"
  },
  {
    "slug": "walking-aid-balance-household-route-udaipur",
    "title": "Exercise Physiology in Udaipur: Walking-Aid C…",
    "citySlug": "udaipur",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "hand-wrist-kitchen-grip-rehabilitation-ahmedabad",
    "title": "Hand and Wrist Rehabilitation in Ahmedabad: S…",
    "citySlug": "ahmedabad",
    "discipline": "physiotherapy"
  },
  {
    "slug": "heat-hydration-appetite-rehabilitation-nutrition-ahmedabad",
    "title": "Nutrition in Ahmedabad: Heat, Hydration, and…",
    "citySlug": "ahmedabad",
    "discipline": "nutrition"
  },
  {
    "slug": "standing-work-tolerance-exercise-physiology-ahmedabad",
    "title": "Exercise Physiology in Ahmedabad: Rebuilding…",
    "citySlug": "ahmedabad",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "dizziness-balance-assessment-physiotherapy-lucknow",
    "title": "Balance Physiotherapy in Lucknow: What a Dizz…",
    "citySlug": "lucknow",
    "discipline": "physiotherapy"
  },
  {
    "slug": "protein-distribution-strength-recovery-nutrition-lucknow",
    "title": "Nutrition in Lucknow: Protein Questions When…",
    "citySlug": "lucknow",
    "discipline": "nutrition"
  },
  {
    "slug": "morning-routine-conditioning-after-hospital-stay-lucknow",
    "title": "Exercise Physiology in Lucknow: Rebuilding a…",
    "citySlug": "lucknow",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "shoulder-overhead-household-reach-physiotherapy-chandigarh",
    "title": "Shoulder Physiotherapy in Chandigarh: Safer O…",
    "citySlug": "chandigarh",
    "discipline": "physiotherapy"
  },
  {
    "slug": "taste-change-nausea-meal-intake-nutrition-chandigarh",
    "title": "Nutrition in Chandigarh: Taste Change, Nausea…",
    "citySlug": "chandigarh",
    "discipline": "nutrition"
  },
  {
    "slug": "talk-test-recovery-monitoring-chosen-activity-chandigarh",
    "title": "Exercise Physiology in Chandigarh: Using Reco…",
    "citySlug": "chandigarh",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "hand-wrist-carrying-load-rehabilitation-surat",
    "title": "Hand and Wrist Rehabilitation in Surat: Asses…",
    "citySlug": "surat",
    "discipline": "physiotherapy"
  },
  {
    "slug": "meal-timing-food-access-rehabilitation-nutrition-surat",
    "title": "Nutrition in Surat: Meal Timing and Food Acce…",
    "citySlug": "surat",
    "discipline": "nutrition"
  },
  {
    "slug": "walking-cycling-endurance-recovery-exercise-physiology-surat",
    "title": "Exercise Physiology in Surat: Rebuilding a Me…",
    "citySlug": "surat",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "post-surgery-morning-movement-physiotherapy-indore",
    "title": "Post-Surgery Physiotherapy in Indore: Making…",
    "citySlug": "indore",
    "discipline": "physiotherapy"
  },
  {
    "slug": "appetite-medication-changes-rehabilitation-nutrition-indore",
    "title": "Nutrition in Indore: Appetite and Medication…",
    "citySlug": "indore",
    "discipline": "nutrition"
  },
  {
    "slug": "outdoor-walking-confidence-exercise-physiology-indore",
    "title": "Exercise Physiology in Indore: Rebuilding Con…",
    "citySlug": "indore",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "one-sided-hand-use-household-tasks-neurological-physiotherapy-patna",
    "title": "Neurological Physiotherapy in Patna: One-Side…",
    "citySlug": "patna",
    "discipline": "physiotherapy"
  },
  {
    "slug": "meal-access-after-discharge-rehabilitation-nutrition-patna",
    "title": "Nutrition in Patna: Making Meals Accessible A…",
    "citySlug": "patna",
    "discipline": "nutrition"
  },
  {
    "slug": "exercise-planning-interrupted-sleep-rehabilitation-patna",
    "title": "Exercise Physiology in Patna: Planning Activi…",
    "citySlug": "patna",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "household-lifting-orthopaedic-physiotherapy-ranchi",
    "title": "Orthopaedic Physiotherapy in Ranchi: Returnin…",
    "citySlug": "ranchi",
    "discipline": "physiotherapy"
  },
  {
    "slug": "chewing-pace-meal-fatigue-rehabilitation-nutrition-ranchi",
    "title": "Nutrition in Ranchi: Chewing Pace and Meal Fa…",
    "citySlug": "ranchi",
    "discipline": "nutrition"
  },
  {
    "slug": "safer-room-to-room-turning-geriatric-exercise-ranchi",
    "title": "Geriatric Exercise in Ranchi: Safer Turning B…",
    "citySlug": "ranchi",
    "discipline": "exercise-physiology"
  },
  {
    "slug": "stroke-movement-sequences-physiotherapy-bhubaneswar",
    "title": "Stroke Physiotherapy in Bhubaneswar: Rebuildi…",
    "citySlug": "bhubaneswar",
    "discipline": "physiotherapy"
  },
  {
    "slug": "daily-routine-change-rehabilitation-nutrition-bhubaneswar",
    "title": "Nutrition in Bhubaneswar: When Daily Routines…",
    "citySlug": "bhubaneswar",
    "discipline": "nutrition"
  },
  {
    "slug": "cardiopulmonary-activity-monitoring-exercise-physiology-bhubaneswar",
    "title": "Exercise Physiology in Bhubaneswar: Monitorin…",
    "citySlug": "bhubaneswar",
    "discipline": "exercise-physiology"
  }
] satisfies readonly StateJournalPostSummary[];
