import { appendFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  appointmentTypes,
  blogPosts,
  services,
  telehealthAppointmentTypes,
} from "../src/lib/data";
import { cityJournalPosts } from "../src/lib/city-journal";

const siteRoot = path.resolve(import.meta.dirname, "..");
const clientDataDirectory = path.join(siteRoot, "src", "lib");

const blogIndex = blogPosts.map((post) => ({
  id: post.id,
  slug: post.slug,
  title: post.title,
  excerpt: post.excerpt,
  date: post.date,
  isoDate: post.isoDate,
  category: post.category,
  image: post.image,
  author: post.author,
}));

await mkdir(clientDataDirectory, { recursive: true });

await writeFile(
  path.join(clientDataDirectory, "blog-index.generated.ts"),
  `// Generated by scripts/generate-client-data.ts. Do not edit by hand.
import type { BlogPostSummary } from "./blog-index";

export const blogIndex = ${JSON.stringify(blogIndex, null, 2)} satisfies readonly BlogPostSummary[];
`,
);
await appendFile(
  path.join(clientDataDirectory, "blog-index.generated.ts"),
  '\nexport const journalDiscoveryIndex = blogIndex.filter((post) => !post.id.startsWith("city-guide-"));\n',
);

const cityJournalIndex = cityJournalPosts.map((post) => ({
  id: post.id,
  slug: post.slug,
  title: post.title,
  excerpt: post.excerpt,
  date: post.date,
  isoDate: post.isoDate,
  category: post.category,
  image: post.image,
  author: post.author,
  citySlug: post.citySlug,
  ...(post.discipline ? { discipline: post.discipline } : {}),
}));

await writeFile(
  path.join(clientDataDirectory, "city-journal-index.generated.ts"),
  `// Generated by scripts/generate-client-data.ts. Do not edit by hand.
import type { CityJournalPostSummary } from "./city-journal-index";

export const cityJournalIndex = ${JSON.stringify(cityJournalIndex, null, 2)} satisfies readonly CityJournalPostSummary[];
`,
);

const stateJournalIndex = cityJournalPosts
  .filter((post) => post.discipline)
  .map((post) => ({
    slug: post.slug,
    title: post.title.length > 48 ? `${post.title.slice(0, 45).trimEnd()}…` : post.title,
    citySlug: post.citySlug,
    discipline: post.discipline,
  }));

await writeFile(
  path.join(clientDataDirectory, "state-journal-index.generated.ts"),
  `// Generated by scripts/generate-client-data.ts. Do not edit by hand.
import type { StateJournalPostSummary } from "./state-journal-index";

export const stateJournalIndex = ${JSON.stringify(stateJournalIndex, null, 2)} satisfies readonly StateJournalPostSummary[];
`,
);

await writeFile(
  path.join(clientDataDirectory, "site-data.generated.ts"),
  `// Generated by scripts/generate-client-data.ts. Do not edit by hand.

export const services = ${JSON.stringify(services, null, 2)} as const;

export const appointmentTypes = ${JSON.stringify(appointmentTypes, null, 2)} as const;

export const telehealthAppointmentTypes = ${JSON.stringify(telehealthAppointmentTypes, null, 2)} as const;
`,
);